### PR TITLE
Romanian translation

### PR DESCRIPTION
**Pull request by RoUnit3d**
Romanian translation

### CODE REVIEW

**Comment by aidenaio** [comment]
hey, thanks for your input!

put some comments

**Comment by RoUnit3d** [comment]
> hey, thanks for your input!
> 
> put some comments

Done, hope that's ok. 👍

**Comment by aidenaio** [comment]
> > hey, thanks for your input!
> > put some comments
> 
> Done, hope that's ok. 👍



> > hey, thanks for your input!
> > put some comments
> 
> Done, hope that's ok. 👍

do i miss some commits?

**Comment by RoUnit3d** [comment]
> > > hey, thanks for your input!
> > > put some comments
> > 
> > 
> > Done, hope that's ok. 👍
> 
> > > hey, thanks for your input!
> > > put some comments
> > 
> > 
> > Done, hope that's ok. 👍
> 
> do i miss some commits?

I get it now, (") was missing, i think i deleted it during the translation process :) hope it's alright now 👍

**Comment by aidenaio** [comment]
sure, i'll take a look
thanks 🎩

**Comment by aidenaio** [comment]
merging in https://github.com/idena-network/idena-desktop/tree/add-ro-translation so i can make changes on it

**Pull request merged**
