### PR TITLE
sr-Latin variant

### PR DESCRIPTION
**Pull request by rioda-org**

### CODE REVIEW

**Comment by aidenaio** [comment]
the build is 🔴 and not feature-complete

may i close this one?

**Comment by rioda-org** [comment]
Well, I tried on my own to add this additional language-variant. Don't know was I able to do this or just you are able to make it? Is there any other way so I can make this or...?

**Comment by aidenaio** [comment]
got you!

sure you can. a bit of coding needed though 

here is the complete example of _adding_ new lang https://github.com/idena-network/idena-desktop/pull/137

hih

**Comment by aidenaio** [comment]
closing

**Pull request closed without merging**
