### PR TITLE
translate node settings page

### PR DESCRIPTION
**Pull request by Johann-S**
Build failed seems the same error I have in #208

### CODE REVIEW

**Comment by aidenaio** [comment]
great work!
much thanks 👊👍

**Comment by aidenaio** [comment]
could you plz upate this as well as #208 🙏

**Comment by Johann-S** [comment]
done, I'll do the same for my other PR 👍

**Comment by aidenaio** [comment]
this will be merged in #234 due to conflicts
can't ask you more for resolving this 😄 

great work man 👍 💯 🥇

**Comment by Johann-S** [comment]
Thanks @aidenaio 👍
I hope I'll be able to contribute more

**Pull request closed without merging**
