### PR TITLE
Update translation.json bulgarian for oracles

### PR DESCRIPTION
**Pull request by DenkoBetona**

### CODE REVIEW

**Comment by aidenaio** [comment]
plz update your i18n definitions

**Comment by DenkoBetona** [comment]
> i mean there are conflicts in the PR, plz resolve

what does PR mean?

**Comment by DenkoBetona** [comment]
> i mean there are conflicts in the PR, plz resolve

sorry mr graham jenson, i dont understand what the problem is

**Comment by aidenaio** [comment]
image
😀 here

**Comment by aidenaio** [comment]
in favor of #561

**Pull request closed without merging**
