### PR TITLE
Update fr for oracles

### PR DESCRIPTION
**Pull request by Syd-ai**
Will update again after release because i need some context of some translations

### CODE REVIEW

**Comment by Syd-ai** [comment]
Updated, should be good now. Will monitor. Thanks 👍

**Comment by Syd-ai** [comment]
wen merge ? @aidenaio ❤️

**Comment by aidenaio** [comment]
> wen merge ? @aidenaio ❤️

hey

planning for the next release.

thank you for your contribution btw 🎩🤜🤛

**Comment by aidenaio** [comment]
plz update your i18n definitions

**Comment by Syd-ai** [comment]
> plz update your i18n definitions

done, thanks

**Pull request merged**
